version: '3.8'

name: proxy-ext-1

services:
  proxy:
    image: itzg/bungeecord:latest
    container_name: proxy-ext-1
    env_file:
      - ./enviroments/proxy-ext-1.env
      - ./enviroments/hosts.env
      - ./secrets/mysql.env
    ports:
      - 25566:25577
    volumes:
      - ./configs/proxy-ext-1:/config
      - ./plugins/proxy-ext-1:/plugins
      - ./servers/proxy-ext-1:/server
