version: '3.8'

name: proxy-main-1

services:
  proxy:
    image: itzg/bungeecord:latest
    container_name: proxy-main-1
    restart: unless-stopped
    user: 1001:1001
    environment:
      - TZ=Asia/Tokyo
    env_file:
      - ./enviroments/proxy-main-1.env
      - ./enviroments/hosts.env
      - ./secrets/mysql.env
    ports:
      - 25565:25577
    volumes:
      - ./configs/proxy-main-1:/config
      - ./plugins/proxy-main-1:/plugins
      - ./data/proxy-main-1:/server
