version: '3.8'

name: backend-limbo-1

services:
  backend:
    image: itzg/minecraft-server:latest
    container_name: limbo
    restart: unless-stopped
    user: 1001:1001
    environment:
      - TZ=Asia/Tokyo
    env_file:
      - ./enviroments/limbo.env
    volumes:
      - ./configs/limbo:/config
      - ./data/limbo:/data
