version: '3.8'

services:
  proxy:
    image: itzg/bungeecord:latest
    env_file:
      - ./enviroments/minecraft.env
      - ./enviroments/proxy.env
    ports:
      - 25565:25577
    volumes:
      - ./plugins/proxy:/plugins
      - ./servers/proxy:/server
