#
# NanoLimbo configuration
#

# Server's host address and port. Set ip empty to use public address
bind:
  ip: '0.0.0.0'
  port: 65535

# Max amount of players can join to server
# Set -1 to make it infinite
maxPlayers: 100

# Server's data in servers list
ping:
  description: '{"text": "Limbo"}'
  version: 'MCPlayNetwork'
  # Return static protocol version number in ping result
  # By default, its -1 to return the client version, if it supported
  # https://wiki.vg/Protocol_version_numbers
  protocol: -1

# Available dimensions: OVERWORLD, NETHER, THE_END
dimension: THE_END

# Whether to display the player in the player list
# For 1.16.5 clients, player list will be sent even if disabled, to avoid crash
playerList:
  enable: false
  username: 'Limbo'

# Whether to display header and footer in player list
# For 1.8+ clients
headerAndFooter:
  enable: false
  header: '{"text": "&eWelcome!"}'
  footer: '{"text": "&9Limbo"}'

# Setup player's game mode
# 0 - Survival
# 1 - Creative (hide HP and food bar)
# 2 - Adventure
# 3 - Spectator (hide all UI bars)
# Spectator works on 1.8+ clients
gameMode: 1

# Server name which is shown under F3
# For 1.13+ clients
brandName:
  enable: true
  content: 'MCPlayNetwork'

# Message sends when player join to server
joinMessage:
  enable: true
  text: '{"text": "&eここは接続待機サーバです。一定時間で自動的に再接続されます。再接続されない場合は、一度切断してから再度接続してみてください。"}'

# BossBar displays when player join to server
# For 1.9+ clients
bossBar:
  enable: true
  text: '{"text": "ここは接続待機サーバです"}'
  health: 1.0
  # Available colors: PINK, BLUE, RED, GREEN, YELLOW, PURPLE, WHITE
  color: RED
  # Available divisions: SOLID, DASHES_6, DASHES_10, DASHES_12, DASHES_20
  division: SOLID

# Display title and subtitle
# For 1.8+ clients
title:
  enable: true
  # Set title text value empty, if you need only subtitle
  title: '{"text": "&c&lめんてなんすちゅう..."}'
  # Set subtitle text value empty, if you need only title
  subtitle: '{"text": "&3www.mcplay.biz"}'
  # Fade in time in ticks (1 sec = 20 ticks)
  fadeIn: 10
  # Stay time in ticks
  stay: 300
  # Fade out time in ticks
  fadeOut: 10

# Player info forwarding support.
# Available types:
#  - NONE
#  - LEGACY
#  - MODERN
#  - BUNGEE_GUARD
# Don't use secret if you not use MODERN type
infoForwarding:
  type: NONE
  secret: '<YOUR_SECRET_HERE>'
  tokens:
    - '<BUNGEE_GUARD_TOKEN>'

# Read timeout for connections in milliseconds
readTimeout: 30000

# Define log level. For production, I'd recommend to use level 2
# Log levels:
# 0 - Display only errors
# 1 - Display errors, warnings
# 2 - Display errors, warnings, info
# 3 - Display errors, warnings, info, debug
debugLevel: 2

# Warning! Do not touch params of this block, if you not completely sure what is this!
netty:
  # Use Linux native transport type, if it possible
  useEpoll: true
  # EventLoopGroup threads count
  threads:
    bossGroup: 1
    workerGroup: 4

# [Experimental]
# Options to check incoming traffic and kick potentially malicious connections.
# Take into account that player can send many small packets, for example just moving mouse.
traffic:
  # If true, then additional handler will be added to channel pipeline
  enable: false
  # Max packet size in bytes
  # Unlimited if -1
  packetSize: 1024
  # How many packets per second allowed for single connection
  # Ignored if -1
  packets: -1
  # How many bytes per second allowed for single connection
  # Ignored if -1
  bytes: 2048